app = "moondao-space-server"
primary_region = "sjc"

[build]

[env]
  NODE_ENV = "production"
  PORT = "8080"

[http_service]
  internal_port = 2567
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1

[deploy]
  release_command = "echo 'Deployment complete'"

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1