app = "moondao-space-server"
primary_region = "sjc"

[build]

[env]
  NODE_ENV = "production"
  PORT = "2567"

[[services]]
  protocol = "tcp"
  internal_port = 2567

  [[services.ports]]
    port = 80
    handlers = ["http"]
    force_https = true

  [[services.ports]]
    port = 443
    handlers = ["http", "tls"]

  [services.concurrency]
    type = "connections"
    hard_limit = 1000
    soft_limit = 800

  [[services.http_checks]]
    interval = "10s"
    timeout = "2s"
    grace_period = "5s"
    method = "GET"
    path = "/"
    protocol = "http"
    restart_limit = 0

[deploy]
  release_command = "echo 'Deployment complete'"

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1